Extending Test Bench (Plugins)
==============================

Test Bench offers an API for writing plugins. Internally, Test Bench records all telemetry that goes on during a test run. Plugins are written as subscribers of that telemetry.

=== Defining a Subscriber

Any object can subscribe to telemetry, it just needs to implement methods that correspond to telemetry events. Here is an example of a subscriber that hooks in to the lifecycle of each test:

[source,ruby]
----
module MyPlugin
  class TelemetrySubscription
    def test_started
      puts "About to run a test"
    end

    def test_finished(test_title)
      puts "Just finished running a test: #{test_title}"
    end
  end
end

subscriber = MyPlugin::TelemetrySubscription.new
----

There are many events written to telemetry. Many include an optional argument, which you can access by simply adding a positional argument to your subscriber's event handler method. Here is a list:

[options="header"]
|=============================================================================
| *Event*           | *Description*                         | *Argument*
| +asserted+        | An assertion was made                 | (none)
| +context_entered+ | A +context+ block was entered         | Context title/prose
| +context_exited+  | A +context+ block was exited          | Context title/prose
| +error_raised+    | An error was just raised              | The +Exception+ object
| +file_started+    | One file is about to be executed      | Filename
| +file_finished+   | One file just finished being executed | Filename
| +run_started+     | The entire test run is about to start | (none)
| +run_finished+    | The entire test run just finished     | (none)
| +test_started+    | A test is about to be executed        | Test title/prose
| +test_finished+   | A test just finished being executed   | Test title/prose
| +test_passed+     | A test just passed                    | Test title/prose
| +test_failed+     | A test just failed                    | Test title/prose
| +test_skipped+    | A test was just skipped               | Test title/prose
|=============================================================================

=== Attaching a Subscriber to Telemetry

Any subscriber can be attached to Test Bench's telemetry via +TestBench::Telemetry.subscribe+:

[source,ruby]
----
subscriber = MyPlugin::TelemetrySubscription.new

TestBench::Telemetry.subscribe subscriber
----
