Rationale
=========

There are already numerous test frameworks for ruby, but Test Bench offers something quite different. Test Bench has a very small API with few methods or method parameters to learn. No mocking library is provided; you are expected to construct your own doubles and substitute them for dependencies. Test files are structured using +context+ and +test+ -- which are analogous to +describe+ or +context+ and +specify+ or +it+, respectively, from RSpec or +minitest/spec+. +assert+ is very simple method; no elaborate matchers are provided to output elaborate assertion failure messages. Additionally, the test files are executed as they are loaded in a single pass. Finally, the output format breaks from the standard "green dots" common to other test frameworks; the prose included in +context+ and +test+ blocks are written to +stdout+ with their nesting intact. These design choices are explained in detail below.

=== No Mocking Necessary

There are generally two reasons to pass in a double to a test subject; to prevent the test subject from triggering behavior on a "real" dependency, and to verify the test subject's interaction with the dependency in isolation. In both cases, either pure null objects or specialized substitutes that mimic the dependency are preferable over a mock. Mocks bind to the actual method calls of the dependency, causing test code to couple to implementation details. Specialized substitutes can act as test doubles _and_ publish their own interface for verifying their use by test subject. For instance, a substitute for a payment processor can implement a method named +charged?(amount)+ that returns true if a certain amount was charged. The implementation of the substitute can then be kept current with the implementation of the payment processor itself without ever necessitating pervasive changes to every test where the payment processor is a dependency of the test subject.

The approach can be seen in the test suite for Test Bench itself; no mocks are used. Just dependency inversion and substitution.

=== Simple Test Structure

Test files are arranged via two methods: +context+ and +test+:

[source,ruby]
----
context "Arithmetic" do
  context "Multiplication" do
    test "Anything multiplied by zero is zero" do
      # ...
    end
  end
end
----

The purpose of +context+ is to narrow the scope of what is being tested. No sentences need be constructed by conjoining the prose supplied to the various +context+ and +test+ blocks. The test output indents the nested blocks to enable human review of the prose:

----
# ruby tests/arithmetic.rb
Arithmetic
  Multiplication
    Anything multiplied by zero is zero
----

This is quite similar to +describe+ and +context+ in RSpec, but without any intention of being used for actually connecting the prose into sentences. In addition, the blocks don't also perform the double duty of providing hooks for altering the tests defined within the block. Data can be shared across tests naturally by simply leveraging the closure provided by the blocks.

=== Just Assert

Unlike RSpec, which offers an API for defining custom matchers, and +test/unit+ and Minitest, which offer many different assertion methods designed to format errors for human readability, Test Bench simply ships with +assert+. This is intentional; while detailed error output is useful when working on a test, the output is often confusing down the road when the code under test regresses. This is because a matcher output will inevitably leak implementation details of the test itself, which are not at all apparent when the user is operating outside the context of the implementation -- for instance, when the build breaks on a CI server.

One feature offered by Test Bench's assertion mechanism is the ability to extend modules that define _customized_ assertion predicates on test subjects. This is discussed in detail in the link:Assertions.adoc[assertions] guide.

It is possible that in the future link:https://github.com/k-tsj/power_assert[Power Assert] will be integrated to offer improved assertion failure output messages.

=== Single Pass Execution

Test Bench does not load all the files containing tests and _then_ run them. Instead, it runs the test files as they are loaded. This greatly simplifies the framework at the expense of some potentially valuable features. Principally, this means that test order cannot be randomized within a single file. Test order randomization is a valid and valuable countermeasure against writing implementations or tests that couple to global state. However, avoiding global state and temporal coupling is also a skill that can be learned over time. In exchange for deterministic ordering, the behavior of a test file under Test Bench is extremely easy to follow; there is no `let`, `setup`, or any other hooks into the test lifecycle because there is no test lifecycle apart from the flow of the test. There is _one_ way to share data across tests, and that is to leverage the closures provided naturally by +context+ blocks. See below, where +number+ is shared across two tests:

[source,ruby]
----
context "Addition" do
  number = 1

  test "Adding zero returns the number" do
    result = number + 0
    assert result == number
  end

  test "Adding one returns one plus the number" do
    result = number + 1
    assert result == 2
  end
end
----

Of course, RSpec's +let+ offers the ability to only load the value when it is dereferenced, often leading to performance improvements. However, +let+ often leads to extremely confusing test files, where it is seldom apparent what variables or state are in play for a given test.

=== Output

There is a single output format for Test Bench, and it resembles RSpec's original spec output. The intention is to enable human review of the prose that is used to describe the tests and contexts. In practice, green dots offer absolutely no useful information, and they obscure all that prose, which tends to lead to bizarre test descriptions that remain unchanged even as implementation drifts.

**Next**: link:Basic-Usage.adoc[Basic Usage]
